name: tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python:
          - '3.9'
          - '3.10'
          - '3.11'
          - pypy-3.9
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install Python dependencies
        run: |
          python -m pip install Markdown python-markdown-math pymdown-extensions
          python -m pip install docutils textile pygments codecov PyYAML
          python -m pip install lxml asciidoc
      - name: Install the project
        run: python setup.py install
      - name: Run tests
        run: coverage run -m unittest discover -s tests -v
      - name: Run the doctest
        run: python -m doctest README.rst -v
      - name: Upload reports to Codecov
        if: ${{ matrix.python == '3.11' }}
        run: codecov
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install flake8, isort and mypy
        run: |
          python -m pip install flake8 isort mypy
          python -m pip install types-docutils types-PyYAML types-Markdown
      - name: Run flake8
        run: flake8 --max-line-length=88 .
      - name: Run isort
        run: isort --check-only .
      - name: Run mypy
        run: mypy --ignore-missing-imports --strict .
